# Generated by Django 3.0.14 on 2022-12-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('texto', models.TextField(max_length=200)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
