# Generated by Django 3.0.14 on 2022-12-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
