# Generated by Django 3.0.14 on 2022-12-22 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
