# Generated by Django 4.1.4 on 2022-12-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='fecha',
        ),
        migrations.AddField(
            model_name='mensajes',
            name='leido',
            field=models.BooleanField(default=False),
        ),
    ]
