# Generated by Django 4.1.4 on 2022-12-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0002_remove_mensajes_fecha_mensajes_leido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensajes',
        ),
    ]
